[package]
name = "rcat"
version = "0.1.0"
authors = ["nabeen <watanabe_kenichiro@hasigo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
